language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libxml2-dev
    - libkml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake         ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libkml        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libxml2       ;fi

install:
  - git clone https://github.com/physycom/sysconfig.git
  - export WORKSPACE=$(pwd)
  - mkdir build && cd build

script:
  - cmake ..
  - cmake --build .
