#define INSUFFICIENT_COMMAND_LINE_PARAMETERS 1
#define FILE_NOT_DECLARED                    2
#define FILE_NOT_FOUND                       3
#define INVALID_KMZ                          4
#define INVALID_KML                          5
#define CORRUPT_FILE_IN_KMZ                  6
#define MISSING_LAT_LON                      7
#define INVALID_NESTED_HTML                  8
#define EMPTY_NESTED_HTML                    9
#define UNEXPECTED_LINE_LENGTH               10
#define FAILED_STOD                          11
